### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
I can't enable Travis on this repository because Travis won't currently show any repos in my orgs :-/

**Comment by Bjwebb** [comment]
Is this another travis-ci.org vs travis-ci.com issue?

**Comment by odscjames** [comment]
Probably. If I go to the latter I get a scary migration thing :-/

**Comment by odscjames** [comment]
I'm probably going to cancel this in favour of GitHub Actions

**Comment by odscjames** [comment]
#3 will do this one.

**Pull request closed without merging**
